### ISSUE TITLE
could you make it work with png/gifs as well?

### ISSUE THREAD

**Issue by vesper8** [softon/laravel-face-detect#1]
Thanks for making this! I tried it out on my video game website where people upload screenshots of their in-game avatars and this library works perfectly!! Very impressed!

Unfortunately it doesn't work when trying to deal with pngs (of which I have many) and gifs (of which I have a few)

Any chance you could update it to work with those too?

**Comment by softon** [comment]
you can use imagecreatefrompng and imagecreatefromgif and use the resource returned to the face detect function it will accept for the time  being. we will update the code for the next release with this issue resolved. Thanks for noticing.
