### ISSUE TITLE
black square but no error

### ISSUE THREAD

**Issue by vesper8** [softon/laravel-face-detect#3]
i noticed that about 10-20% of the time the face detection doesn't fail but it creates a black square instead of a piece of the image, ideally containing a face

it doesn't create an error though, and it does work the majority of the time

i made sure it isn't an issue with the wrong mime type either. though it's not impossible there's something wrong with the image, it seems ok otherwise

**Comment by vesper8** [comment]
here's a sample that is creating the black square. i know it's a video game however i've run your face detection on thousands of similar video game screenshots and the face detection works the majority of the time

![7cedf7d2cb0027c2a05a38ea6ff7d425](https://user-images.githubusercontent.com/816028/31313092-1b97cc2c-aba6-11e7-94b3-6f622549d6bc.jpg)
![face](https://user-images.githubusercontent.com/816028/31313091-1b92eb8a-aba6-11e7-9266-360183325e4b.jpg)

this one also doesn't work

![c3d001c95f01e2da00403d8561621d52](https://user-images.githubusercontent.com/816028/31313094-28fd6642-aba6-11e7-84a6-98cdf22e945f.jpg)
![face](https://user-images.githubusercontent.com/816028/31313095-28ff4368-aba6-11e7-8075-202e4d077459.jpg)

but these two work:

![42dc2ca0c5dd9bb8e6a82e01471d0988](https://user-images.githubusercontent.com/816028/31313098-31a4b110-aba6-11e7-9c2c-04da2966db4c.jpg)
![face](https://user-images.githubusercontent.com/816028/31313097-31a3e8ca-aba6-11e7-9cfa-9b74d1a67e65.jpg)

![55a44b9e1996cdfb4de264b16225fc5f](https://user-images.githubusercontent.com/816028/31313100-4309cd00-aba6-11e7-94ff-c82629d5387f.jpg)
![face](https://user-images.githubusercontent.com/816028/31313101-430c3a54-aba6-11e7-9d17-bb177a138604.jpg)

any help in resolving this is much appreciated!

**Comment by softon** [comment]
yeah sometimes if png and gif images or if it fails to detect any face it returns black screen.
